# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'
    steps:    
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(3df088ff-764b-4f71-95c2-bad9920dcb72)'
        azureContainerRegistry: '{"loginServer":"mmaltes1containerregistry.azurecr.io", "id" : "/subscriptions/3df088ff-764b-4f71-95c2-bad9920dcb72/resourceGroups/myapp-rg/providers/Microsoft.ContainerRegistry/registries/mmaltes1ContainerRegistry"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        includeSourceTags: true
        includeLatestTag: true
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(3df088ff-764b-4f71-95c2-bad9920dcb72)'
        azureContainerRegistry: '{"loginServer":"mmaltes1containerregistry.azurecr.io", "id" : "/subscriptions/3df088ff-764b-4f71-95c2-bad9920dcb72/resourceGroups/myapp-rg/providers/Microsoft.ContainerRegistry/registries/mmaltes1ContainerRegistry"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
        includeSourceTags: true
        includeLatestTag: true
